name: Node.js CI

on:
  push:
    branches: [ main, develop ] # Triggers on push to main or develop branches
  pull_request:
    branches: [ main, develop ] # Triggers on pull requests targeting main or develop

jobs:
  build-and-test:
    runs-on: [self-hosted, ip-172-31-86-157]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your code

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Action to set up Node.js environment
      with:
        node-version: '20.x' # Specify the Node.js version

    - name: Install dependencies
      run: npm ci # Installs dependencies (npm ci is recommended for CI)

    - name: Run tests
      run: npm test # Runs your project's tests
