name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**' # Triggers on pull requests to any branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint # Assuming you have a 'lint' script in package.json

  test:
    runs-on: ubuntu-latest
    needs: lint # This job will only run after the 'lint' job completes successfully
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # Assuming you have a 'test' script in package.json
